spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mosidian
    password: 2020mosiDian@
    url: jdbc:mysql://www.mosidian.com:3306/mosidian_pro?characterEncoding=utf-8&useSSL=false

  jackson:
    default-property-inclusion: non_null
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: www.mosidian.com:6379
    port: 6379
    password: 2020mosdian@
    lettuce:
      #    jedis:
      pool:
        # 连接池最大连接数，负数表示不限制
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 60000

  rabbitmq:
    addresses: www.mosidian.com
    port: 5672
    username: mosidian
    password: 2020mosdidian@

  # session 存储方式
  session:
    store-type: redis
    timeout: 1200

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /mall
  port: 8083
